variables:
  headless: "true"
build:
  stage: build
  image: nexus.nico-dreher.de:8084/maven-jfx:latest
  script:
    - mvn test --fail-never
    - mvn package -Dmaven.test.skip=true
    - mvn javadoc:aggregate -Dmaven.test.skip=true
    - cp -r target/site/apidocs/ javadoc
    - mv target/Kontaktsplitter-Kings.jar Kontaktsplitter-Kings.jar
  artifacts:
    paths:
      - Kontaktsplitter-Kings.jar
      - javadoc/
      - start.bat
      - start.sh
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
