stages:
  - docs
  - build
  - bundle
variables:
  headless: "true"
docs:
  stage: docs
  image:
    name: fiware/md2pdf:0.2.2
    entrypoint: [""]
  script:
    - rm /usr/local/lib/python2.7/dist-packages/markdown_to_pdf-0.2.2-py2.7.egg/markdown_to_pdf/cover_template/cover_template.md
    - cp -r docs/cover/. /usr/local/lib/python2.7/dist-packages/markdown_to_pdf-0.2.2-py2.7.egg/markdown_to_pdf/cover_template
    - ls /usr/local/lib/python2.7/dist-packages/markdown_to_pdf-0.2.2-py2.7.egg/markdown_to_pdf/cover_template
    - markdown_to_pdf -i docs.yml -o documentation.pdf
  artifacts:
    paths:
      - documentation.pdf
build:
  stage: build
  image: nexus.nico-dreher.de:8084/maven-jfx:latest
  script:
    - mvn test --fail-never
    - mvn package -Dmaven.test.skip=true
    - mvn javadoc:aggregate -Dmaven.test.skip=true
    - cp -r target/site/apidocs/ javadoc
    - mv target/Kontaktsplitter-Kings.jar Kontaktsplitter-Kings.jar
  artifacts:
    paths:
      - Kontaktsplitter-Kings.jar
      - javadoc/
      - start.bat
      - start.sh
      - documentation.pdf
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
bundle:
  stage: bundle
  image: nexus.nico-dreher.de:8084/maven-jfx:latest
  script:
    - if [ ! -d "openjdk-11" ]; then echo "Downloading OpenJDK"; wget https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_windows-x64_bin.zip; unzip openjdk-11+28_windows-x64_bin.zip -d ./; mv jdk-11/ openjdk-11/; else; echo "OpenJDK Cached"; fi
  cache:
    paths:
      - openjdk-11/
  artifacts:
    paths:
      - Kontaktsplitter-Kings.jar
      - javadoc/
      - openjdk-11/
      - start.bat
      - start.sh
      - start-bundle.bat
      - documentation.pdf