stages:
  - build
  - bundle
variables:
  headless: "true"
build:
  stage: build
  image: nexus.nico-dreher.de:8084/maven-jfx:latest
  script:
    - mvn test --fail-never
    - mvn package -Dmaven.test.skip=true
    - mvn javadoc:aggregate -Dmaven.test.skip=true
    - cp -r target/site/apidocs/ javadoc
    - mv target/Kontaktsplitter-Kings.jar Kontaktsplitter-Kings.jar
  artifacts:
    paths:
      - Kontaktsplitter-Kings.jar
      - javadoc/
      - start.bat
      - start.sh
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
bundle:
  stage: bundle
  image: nexus.nico-dreher.de:8084/maven-jfx:latest
  script:
    - wget https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_windows-x64_bin.zip
    - unzip openjdk-11+28_windows-x64_bin.zip -d ./
    - mv jdk-11/ openjdk-11/
  artifacts:
    paths:
      - Kontaktsplitter-Kings.jar
      - javadoc/
      - openjdk-11/
      - start.bat
      - start.sh
      - start-bundle.bat