variables:
  headless: "true"
build:
  stage: build
  image: maven:latest
  script:
    - mvn test --fail-never
    - mvn package javadoc:aggregate -Dmaven.test.skip=true
    - cp -r target/site/apidocs/ javadoc
    - mv target/Kontaktsplitter-Kings.jar Kontaktsplitter-Kings.jar
  artifacts:
    paths:
      - Kontaktsplitter-Kings.jar
      - javadoc/
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
